version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - "APP_NAME=${APP_NAME}"
        - "WORKDIR=/${APP_NAME}"
        - "USER_NAME=${USER_NAME:-root}"
        - "USER_ID=${USER_ID:-0}"
        - "GROUP_NAME=${GROUP_NAME:-root}"
        - "GROUP_ID=${GROUP_ID:-0}"
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    container_name: "${APP_NAME}_app"
    #command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    command: /bin/sh -c "bundle install"
    environment:
      RAILS_ENV: "${RAILS_ENV:-development}"
    volumes:
      - ".:/${APP_NAME}"
    ports:
      - "${APP_PORT:-3000}:3000"
