version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - "APP_NAME=${APP_NAME}"
        - "WORKDIR=/${APP_NAME}"
        - "USER_NAME=${USER_NAME:-root}"
        - "USER_ID=${USER_ID:-0}"
        - "GROUP_NAME=${GROUP_NAME:-root}"
        - "GROUP_ID=${GROUP_ID:-0}"
    container_name: "${APP_NAME}_app"
    volumes:
      - ".:/${APP_NAME}"
