#!/usr/bin/env ruby

require 'bundler'
Bundler.require

require_relative 'app/csv_generator'

opts = Optimist::options do
  version '0.0.1'
  banner <<~USAGE
    Usage:
      1. new <name>
      2. edit line/<name>/...
      3. factory <name> +[options] # <= Now here

    Currently available <name>:
    #{Dir.glob('line/*').map{|path| ['  ', File.basename(path)].join }.join("\n") }

    where [options] are:
    USAGE
  opt :row_count, 'default: 10',             short: :c, type: :integer
  opt :file,      'default: "rollout.csv"',  short: :f, type: :string
  opt :header,    'default: "true"',         short: :H, type: :string
  opt :separator, 'default: ","',            short: :s, type: :string
  opt :quotes,    'default: "false"',        short: :q, type: :string
  opt :config,    'config overwrite(JSON)',  short: :o, type: :string
  opt :bom,       'With BOM',                short: :b, type: :boolean
  opt :shift_jis, 'Output with shift_jis',   short: :S, type: :boolean
  opt :win31j,    'Output with Windows31J',  short: :W, type: :boolean
end

options = {}
options[:file]      = opts.file if opts.file
options[:row_count] = opts.row_count if opts.row_count
options[:separator] = opts.separator if opts.separator
options[:header]    = { true: true, false: false }[opts.header.to_sym] unless opts.header.nil?
options[:quotes]    = { true: true, false: false }[opts.quotes.to_sym] unless opts.quotes.nil?
options[:bom]       = opts.bom if opts.bom
options[:shift_jis] = opts.shift_jis if opts.shift_jis
options[:win31j]    = opts.win31j if opts.win31j

options.merge!(JSON.parse(opts.config || '{}', symbolize_names: true))

Faker::Config.locale = :ja

CsvGenerator.run(ARGV[0].split("/").last, **options)
