#!/bin/sh
usage_exit() {
  cat << EOS
    Usage: $0 some_name
      created modules in line/some_name
EOS
  exit 0
}

NAME=$1

# 空文字ダメ
if [ -z "$NAME" ]; then
  echo "name is empty"
  exit 1
fi

if [ $NAME = "-h" ]; then
  usage_exit
fi

# すでにある名前もダメ
if [ -e "line/$NAME" ]; then
  echo already exists $NAME
  exit 1
else
  # テンプレートをコピー
  cp -rf line/template line/$NAME
fi

# パスカルケースへ
CLASS_NAME=`echo $NAME | awk -F '_' '{ for(i=1; i<=NF; i++) {printf toupper(substr($i,1,1)) substr($i,2)}} END {print ""}'`

# テンプレートのクラス名などを置換
find "line/$NAME" -name "*.rb" -or -name "*.yml" | xargs sed -i "s/[tT]emplate/${CLASS_NAME}/g"
