# param:  Param.instance
# cursor: row index
# id:     serial number from start_id
module ImportCo
  module Row
    def columns
      [
        column(header: "発注管理ID", key: :send_number, render: -> { "#{param.send_number_prefix}_#{id}" }),
        column(header: "受注管理ID", key: :receive_number, render: -> { "#{param.receive_number_prefix}_#{id}" }),
        column(header: "元伝票発注ID", key: :src_id, render: -> { 0 } ),
        column(header: "元伝票発注名", key: :src_name),
        column(header: "元伝票発注管理ID", key: :src_send_number),
        column(header: "元伝票受注管理ID", key: :src_receive_number),
        column(header: "見積ID", key: :ce_id, render: -> { 0 } ),
        column(header: "見積名", key: :ce_name),
        column(header: "見積管理ID（発注側）", key: :ce_send_number),
        column(header: "見積管理ID（受注側）", key: :ce_receive_number),
        column(header: "発注会社ID", key: :send_client_id, render: -> { param.send_client[:id] }),
        column(header: "発注会社", key: :send_client_name, render: -> { param.send_client[:name] }),
        column(header: "受注会社ID", key: :receive_client_id, render: -> { param.receive_client[:id] }),
        column(header: "受注会社", key: :receive_client_name, render: -> { param.receive_client[:name] }),
        column(header: "取引先ID", key: :contract_id, render: -> { param.contract[:id] }),
        column(header: "取引先", key: :contract_name, render: -> { param.contract[:name] }),
        column(header: "取引先管理ID", key: :contract_number, render: -> { param.contract[:number] }),
        column(header: "取引設定ID", key: :cs_id, render: -> { param.contract_setting[:id] }),
        column(header: "取引設定名", key: :cs_name, render: -> { param.contract_setting[:name] }),
        column(header: "取引設定管理ID（発注側）", key: :cs_number, render: -> { param.contract_setting[:external_send_contract_setting_number] }),
        column(header: "案件ID", key: :order_id, render: -> { param.order[:id] }),
        column(header: "案件名", key: :order_name, render: -> { param.order[:site_name] }),
        column(header: "案件管理ID", key: :order_number, render: -> { param.order[:common_id] }),
        column(header: "発注名", key: :contract_order_name, render: -> { [Faker::Games::Pokemon.name, id].join("_") }),
        column(header: "ステータス", key: :status),
        column(header: "前ステータス", key: :prev_status),
        column(header: "発注方法", key: :order_method),
        column(header: "担当者ID（発注側）", key: :send_user_id, render: -> { param.user[:id] }),
        column(header: "担当者（発注側）", key: :send_user_name, render: -> { param.user[:name] }),
        column(header: "担当者ID（受注側）", key: :receive_user_id, render: -> { param.receive_user[:id] }),
        column(header: "担当者（受注側）", key: :receive_user_name, render: -> { param.receive_user[:name] }),
        column(header: "現場監督ID", key: :foreman_user_idd, render: -> { param.user[:id] }),
        column(header: "現場監督", key: :foreman_user_named, render: -> { param.user[:name] }),
        column(header: "発注者ID", key: :ordered_user_id, render: -> { param.user[:id] }),
        column(header: "発注者", key: :ordered_user_name, render: -> { param.user[:name] }),
        column(header: "受注者ID", key: :contractor_user_id, render: -> { param.receive_user[:id] }),
        column(header: "受注者", key: :contractor_name, render: -> { param.receive_user[:name] }),
        column(header: "発注金額（税抜）", key: :price, render: -> { param.price } ),
        column(header: "発注金額（税込）", key: :price_with_tax, render: -> { param.price_with_tax } ),
        column(header: "発注金額（税額）", key: :tax_price, render: -> { param.tax_price } ),
        column(header: "課税状況", key: :taxation_status),
        column(header: "税率", key: :tax_rate),
        column(header: "出来高払いフラグ", key: :piecework_flg),
        column(header: "添付フラグ", key: :attachment_flg),
        column(header: "発注日", key: :orderd_date),
        column(header: "請負日", key: :respond_date),
        column(header: "工程開始日", key: :start_date),
        column(header: "工程終了日", key: :end_date),
        column(header: "納品場所タイプ", key: :delivery_type),
        column(header: "納品場所", key: :delivery_location),
        column(header: "発注種別", key: :order_type, render: -> { param.contract_order_types.sample }),
        column(header: "備考（発注側）", key: :send_description),
        column(header: "備考（受注側）", key: :receive_desctiption),
        column(header: "キャンセルフラグ", key: :cancel_flg),
        column(header: "発注作成日時", key: :created_at),
        column(header: "発注更新日時", key: :updated_at),
      ]
    end
  end
end
